service: amiverse-backend

image: kisana-me/amiverse-backend

servers:
  web:
    hosts:
      - <%= ENV.fetch("DEPLOY_HOST", "127.0.0.1") %>
    options:
      add-host: host.docker.internal:host-gateway

proxy:
  ssl: false
  forward_headers: true
  app_port: 80
  healthcheck:
    path: /up
    interval: 3
    timeout: 30

registry:
  server: 127.0.0.1:5000
  username: kamal
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - DB_USERNAME
    - DB_PASSWORD
    - S3_USERNAME
    - S3_PASSWORD
    - MEILISEARCH_API_KEY
    - S3_API_ENDPOINT
    - S3_LOCAL_ENDPOINT
  clear:
    DB_HOST: host.docker.internal
    MEILISEARCH_URL: http://host.docker.internal:7700
    MODERATION_ENDPOINT: http://host.docker.internal:8000

    BACK_URL: https://api.amiverse.net
    FRONT_URL: https://amiverse.net
    S3_REGION: auto
    S3_BUCKET: amiverse
    S3_PUBLIC_ENDPOINT: https://m.amiverse.net

    SOLID_QUEUE_IN_PUMA: true

    # Set number of processes dedicated to Solid Queue (default: 1)
    # JOB_CONCURRENCY: 3

    # Set number of cores available to the application on each server (default: 1).
    # WEB_CONCURRENCY: 2

    # Log everything from Rails
    # RAILS_LOG_LEVEL: debug

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

asset_path: /rails/public/assets

builder:
  arch: amd64
  dockerfile: Dockerfile.production
  driver: docker

ssh:
  user: <%= ENV.fetch("DEPLOY_SSH_USER", "root") %>
  port: <%= ENV.fetch("DEPLOY_SSH_PORT", 22) %>
  keys: [ "~/.ssh/id_kamal" ]
  keys_only: true
